safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 天恩与天泽
host: localhost
desc: 别怕困难，方法总比困难多

custom:
    category:
        default: 默认分类
        another: Another Category
    categories:
      - name:  default
        title: 随笔

      - name:  Java
        title: Java

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: raytz
        email: raymond_ng@qq.com
        disqus: raytz              # Disqus缩略标识
        # gcse:      # Google自定义搜索标识ID
        github: raymond.ng.gz@gmail.com                 # GitHub账号
        gravatar:   # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
